### ISSUE TITLE
No way to determine the percentage of occurrence of a given attribute

### ISSUE THREAD

**Issue by BartoszSolkaArianelabs** [hashgraph/hedera-nft-utilities#31]
### Problem

We would like to have a way to determine how often (percentage-wise) a given attribute occurs in a collection.

![image](https://github.com/hashgraph/hedera-nft-utilities/assets/91123947/f0d8bc15-9ac5-4fe9-baa2-64ff8c2b61be)

### Solution

Return an object of trait_type => {value: "<value>", percent_of_occurrence: <rarity>}

```json
{
  "hat": {
    "Blue": 5,
    "Yellow": 25,
    "White": 70
  },
  "shoes": {
    "Blue": 1,
    "Yellow": 90,
    "White": 9
  }
}
```

**Comment by michielmulders** [comment]
Closed by #32
